#include "utils/ll.h"
#include "models/assembly.h"


/* load instructions and their ids and sizes at initialization */
const instr_map instr_table[] = {
    {"pushw", pushw, 2,
     INS_GRP_PUSH}, // mnemonic, mnem_id, size in bytes, groupid
    {"pushl", pushl, 4, INS_GRP_PUSH},
    {"pushq", pushq, 8, INS_GRP_PUSH},
    {"popw", popw, 2, INS_GRP_POP},
    {"popl", popl, 4, INS_GRP_POP},
    {"popq", popq, 8, INS_GRP_POP},
    {"movb", movb, 1, INS_GRP_MOV},
    {"movw", movw, 2, INS_GRP_MOV},
    {"movl", movl, 4, INS_GRP_MOV},
    {"movq", movq, 8, INS_GRP_MOV},
    {"movzbw", movzbw, 2, INS_GRP_MOV},
    {"movzbl", movzbl, 4, INS_GRP_MOV},
    {"movzbq", movzbq, 8, INS_GRP_MOV},
    {"movzwl", movzwl, 4, INS_GRP_MOV},
    {"movzwq", movzwq, 8, INS_GRP_MOV},
    {"movsbw", movsbw, 2, INS_GRP_MOV},
    {"movsbl", movsbl, 4, INS_GRP_MOV},
    {"movsbq", movsbq, 8, INS_GRP_MOV},
    {"movswl", movswl, 4, INS_GRP_MOV},
    {"movswq", movswq, 8, INS_GRP_MOV},
    {"movslq", movslq, 8, INS_GRP_MOV},
    {"addw", addw, 2, INS_GRP_OP, "+"},
    {"addl", addl, 4, INS_GRP_OP, "+"},
    {"addq", addq, 8, INS_GRP_OP, "+"},
    {"subb", subb, 1, INS_GRP_OP, "-"},
    {"subw", subw, 2, INS_GRP_OP, "-"},
    {"subl", subl, 4, INS_GRP_OP, "-"},
    {"subq", subq, 8, INS_GRP_OP, "-"},
    {"mulb", mulb, 1, INS_GRP_MULTU},
    {"mulw", mulw, 2, INS_GRP_MULTU},
    {"mull", mull, 4, INS_GRP_MULTU},
    {"mulq", mulq, 8, INS_GRP_MULTU},
    {"imulb", imulb, 1, INS_GRP_MULT},
    {"imulw", imulw, 2, INS_GRP_MULT},
    {"imull", imull, 4, INS_GRP_MULT},
    {"imulq", imulq, 8, INS_GRP_MULT},
    {"divb", divb, 1, INS_GRP_DIVU},
    {"divw", divw, 2, INS_GRP_DIVU},
    {"divl", divl, 4, INS_GRP_DIVU},
    {"divq", divq, 8, INS_GRP_DIVU},
    {"idivb", idivb, 1, INS_GRP_DIV},
    {"idivw", idivw, 2, INS_GRP_DIV},
    {"idivl", idivl, 4, INS_GRP_DIV},
    {"idivq", idivq, 8, INS_GRP_DIV},
    {"incb", incb, 1, INS_GRP_INC},
    {"incw", incw, 2, INS_GRP_INC},
    {"incl", incl, 4, INS_GRP_INC},
    {"incq", incq, 8, INS_GRP_INC},
    {"cmpb", cmpb, 1, INS_GRP_CMP},
    {"cmpw", cmpw, 2, INS_GRP_CMP},
    {"cmpl", cmpl, 4, INS_GRP_CMP},
    {"cmpq", cmpq, 8, INS_GRP_CMP},
    {"testb", testb, 1, INS_GRP_TEST},
    {"testw", testw, 2, INS_GRP_TEST},
    {"testl", testl, 4, INS_GRP_TEST},
    {"testq", testq, 8, INS_GRP_TEST},
    {"salb", salb, 1, INS_GRP_OP, "<<"},
    {"salw", salw, 2, INS_GRP_OP, "<<"},
    {"sall", sall, 4, INS_GRP_OP, "<<"},
    {"salq", salq, 8, INS_GRP_OP, "<<"},
    {"sarb", sarb, 1, INS_GRP_OP, ">>"},
    {"sarw", sarw, 2, INS_GRP_OP, ">>"},
    {"sarl", sarl, 4, INS_GRP_OP, ">>"},
    {"sarq", sarq, 8, INS_GRP_OP, ">>"},
    {"shlb", shlb, 1, INS_GRP_OP, "<<"},
    {"shlw", shlw, 2, INS_GRP_OP, "<<"},
    {"shll", shll, 4, INS_GRP_OP, "<<"},
    {"shlq", shlq, 8, INS_GRP_OP, "<<"},
    {"shrb", shrb, 1, INS_GRP_OP, ">>"},
    {"shrw", shrw, 2, INS_GRP_OP, ">>"},
    {"shrl", shrl, 4, INS_GRP_OP, ">>"},
    {"shrq", shrq, 8, INS_GRP_OP, ">>"},
    {"andb", andb, 1, INS_GRP_OP, "&"},
    {"andw", andw, 2, INS_GRP_OP, "&"},
    {"andl", andl, 4, INS_GRP_OP, "&"},
    {"andq", andq, 8, INS_GRP_OP, "&"},
    {"call", call, 0, INS_GRP_CALL},
    {"lcall", lcall, 0, INS_GRP_CALL},
    {"leave", leave, 0},
    {"ret", ret, 0},
    {"lret", lret, 0},
    {"ja", ja, 0, INS_GRP_CJMP},
    {"jae", jae, 0, INS_GRP_CJMP},
    {"jb", jb, 0, INS_GRP_CJMP},
    {"jbe", jbe, 0, INS_GRP_CJMP},
    {"jc", jc, 0, INS_GRP_CJMP},
    {"jcxz", jcxz, 0, INS_GRP_CJMP},
    {"je", je, 0, INS_GRP_CJMP},
    {"jecxz", jecxz, 0, INS_GRP_CJMP},
    {"jg", jg, 0, INS_GRP_CJMP},
    {"jge", jge, 0, INS_GRP_CJMP},
    {"jl", jl, 0, INS_GRP_CJMP},
    {"jle", jle, 0, INS_GRP_CJMP},
    {"jmp", jmp, 0, INS_GRP_JMP},
    {"jnae", jnae, 0, INS_GRP_CJMP},
    {"jnb", jnb, 0, INS_GRP_CJMP},
    {"jnbe", jnbe, 0, INS_GRP_CJMP},
    {"jnc", jnc, 0, INS_GRP_CJMP},
    {"jne", jne, 0, INS_GRP_CJMP},
    {"jng", jng, 0, INS_GRP_CJMP},
    {"jnge", jnge, 0, INS_GRP_CJMP},
    {"jnl", jnl, 0, INS_GRP_CJMP},
    {"jnle", jnle, 0, INS_GRP_CJMP},
    {"jno", jno, 0, INS_GRP_CJMP},
    {"jnp", jnp, 0, INS_GRP_CJMP},
    {"jns", jns, 0, INS_GRP_CJMP},
    {"jnz", jnz, 0, INS_GRP_CJMP},
    {"jo", jo, 0, INS_GRP_CJMP},
    {"jp", jp, 0, INS_GRP_CJMP},
    {"jpe", jpe, 0, INS_GRP_CJMP},
    {"jpo", jpo, 0, INS_GRP_CJMP},
    {"js", js, 0, INS_GRP_CJMP},
    {"jz", jz, 0, INS_GRP_CJMP},
    {"leal", leal, 0, INS_GRP_LEA},
    {"leaq", leaq, 0, INS_GRP_LEA},
    {"int", int3, 0},
    {"ud2", ud2, 0}};

int instr_table_length = sizeof(instr_table) / sizeof(instr_map);
