#include "utils/ll.h"
#include "models/assembly.h"
//load instructions and their ids and sizes at initialization
const instr_map instr_table[] = {
  {"pushw",pushw,2}, // mnemonic, mnem_id, size in bytes
  {"pushl",pushl,4},
  {"pushq",pushq,8},
  {"popw", popw,2}, 
  {"popl", popl,4},
  {"popq", popq,8},
  {"movb", movb,1},
  {"movw", movw,2},
  {"movl", movl,4},
  {"movq", movq,8},
  {"movzbw", movzbw,2},
  {"movzbl", movzbl,4},
  {"movzbq", movzbq,8},
  {"movzwl", movzwl,4},
  {"movzwq", movzwq,8},
  {"movsbw", movsbw,2},
  {"movsbl", movsbl,4},
  {"movsbq", movsbq,8},
  {"movswl", movswl,4},
  {"movswq", movswq,8},
  {"movslq", movslq,8},
  {"addw", addw,2},
  {"addl", addl,4},
  {"addq", addq,8},
  {"subb", subb,1},
  {"subw", subw,2},
  {"subl", subl,4},
  {"subq", subq,8},
  {"mulb", mulb,1},
  {"mulw",mulw,2},
  {"mull",mull,4},
  {"mulq",mulq,8},
  {"imulb", imulb,1},
  {"imulw",imulw,2},
  {"imull",imull,4},
  {"imulq",imulq,8},
  {"cmpb", cmpb,1},
  {"cmpw", cmpw,2},
  {"cmpl", cmpl,4},
  {"cmpq", cmpq,8},
  {"testb", testb, 1},
  {"testw", testw, 2},
  {"testl", testl, 4},
  {"testq", testq, 8},
  {"salb", salb,1},
  {"salw", salw,2},
  {"sall", sall,4},
  {"salq", salq,8},
  {"sarb", sarb,1},
  {"sarw", sarw,2},
  {"sarl", sarl,4},
  {"sarq", sarq,8},
  {"shlb", shlb,1},
  {"shlw", shlw,2},
  {"shll", shll,4},
  {"shlq", shlq,8},
  {"shrb", shrb,1},
  {"shrw", shrw,2},
  {"shrl", shrl,4},
  {"shrq", shrq,8},
  {"andb", andb,1},
  {"andw", andw,2},
  {"andl", andl,4},
  {"andq", andq,8},
  {"call", call},
  {"lcall", lcall},
  {"leave", leave},
  {"ret", ret},
  {"lret", lret},
  {"ja", ja},
  {"jae", jae},
  {"jb", jb},
  {"jbe", jbe},
  {"jc", jc},
  {"jcxz", jcxz},
  {"je", je},
  {"jecxz", jecxz},
  {"jg", jg},
  {"jge", jge},
  {"jl", jl},
  {"jle", jle},
  {"jmp", jmp},
  {"jnae", jnae},
  {"jnb", jnb},
  {"jnbe", jnbe},
  {"jnc", jnc},
  {"jne", jne},
  {"jng", jng},
  {"jnge", jnge},
  {"jnl", jnl},
  {"jnle", jnle},
  {"jno", jno},
  {"jnp", jnp},
  {"jns", jns},
  {"jnz", jnz},
  {"jo", jo},
  {"jp", jp},
  {"jpe", jpe},
  {"jpo", jpo},
  {"js", js},
  {"jz", jz},
  {"int", int3},
  {"ud2", ud2}
};

int instr_table_length = sizeof(instr_table)/sizeof(instr_map);
